version: "3.3"
services:
  webapp:
    image: webserver
    container_name: webserver
    build:
      context: ../
      dockerfile: docker/Dockerfile
    volumes:
      - ${APP_ROOT}src:/var/www/html
      - ${APP_ROOT}access.log:/var/log/apache2/access.log
    ports:
      - 80:80
    depends_on:
      - dbapp
    networks:
      - appnet
  
  dbapp:
    image: mysql:5.7.31
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: therootpasswordserver339017
    volumes:
      - ${APP_ROOT}mysqldata:/var/lib/mysql
    networks:
      - appnet

networks:
  appnet:
    driver: bridge