version: "3.3"
services:
  webapp:
    build:
      context: /home/ixonstater/school/computer-ethics
      dockerfile: docker/dockerfilenginx
    volumes:
      - /home/ixonstater/school/computer-ethics/src:/var/www/html
      - /home/ixonstater/school/computer-ethics/access.log:/var/log/nginx/access.log
    ports:
      - "80:80"
    depends_on:
      - phpimage
    links:
      - phpimage

  phpimage:
    image: php:7-fpm
    volumes:
      - /home/ixonstater/school/computer-ethics/src:/var/www/html
  
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: therootpasswordserver339017
    volumes:
      - /home/ixonstater/school/computer-ethics/mysqldata:/var/lib/mysql
    ports:
      - "33060:3306"